package rules;

import forum.model.Post;
import forum.model.User;
import forum.model.PostLabelEnum;
import forum.model.UserLabelEnum;

import forum.event.DislikePostEvent;
import forum.event.LikePostEvent;
import forum.event.ReportPostEvent;
import forum.event.NewPostEvent;
import forum.event.DefaultUserActionEvent;
import forum.event.LikeQualityPostEvent;
import forum.event.CommunityContributorStreakEvent;
import forum.event.TopUserStreakEvent;

import forum.event.label.TopUserLabelEvent;
import forum.event.label.CommunityContributorUserLabelEvent;
import forum.event.label.SpammerUserLabelEvent;
import forum.event.label.HarmfulUserLabelEvent;
import forum.event.label.TemporarilySuspendedUserLabelEvent;
import forum.event.label.SuspendedUserLabelEvent;

import forum.event.label.TrendingPostLabelEvent;
import forum.event.label.PoorContentPostLabelEvent;
import forum.event.label.PotentiallyHarmfulPostLabelEvent;
import forum.event.label.HarmfulPostLabelEvent;

rule "Poor content detected"
    when
        $post: Post($pId: postId, isPoorContent(), !postLabels.contains(PostLabelEnum.POOR_CONTENT))
    then    
    	insert(new PoorContentPostLabelEvent($pId));
        $post.addLabel(PostLabelEnum.POOR_CONTENT);        
        update($post);
end

rule "Poor content revoked"
    when
        $post: Post($pId: postId, !isPoorContent(), postLabels.contains(PostLabelEnum.POOR_CONTENT))        
    	$e: PoorContentPostLabelEvent(postId == $pId)
    then    
    	delete($e);
        $post.removeLabel(PostLabelEnum.POOR_CONTENT);        
        update($post);
end