package rules;

import forum.model.Post;
import forum.model.User;
import forum.model.PostLabelEnum;
import forum.model.UserLabelEnum;

import forum.event.DislikePostEvent;
import forum.event.LikePostEvent;
import forum.event.ReportPostEvent;
import forum.event.NewPostEvent;

import forum.event.label.TopUserLabelEvent;
import forum.event.label.CommunityContributorUserLabelEvent;
import forum.event.label.SpammerUserLabelEvent;
import forum.event.label.HarmfulUserLabelEvent;
import forum.event.label.TemporarilySuspendedUserLabelEvent;
import forum.event.label.SuspendedUserLabelEvent;

import forum.event.label.TrendingPostLabelEvent;
import forum.event.label.PoorContentPostLabelEvent;
import forum.event.label.PotentiallyHarmfulPostLabelEvent;
import forum.event.label.HarmfulPostLabelEvent;

rule "Post like"
	salience 10
	lock-on-active
    when        
        $e: LikePostEvent($pId: postId)            
        $p: Post(postId == $pId)
    then
    	$p.likePost();
    	update($p);
end

rule "Post dislike"
	salience 10
	lock-on-active
    when        
        $e: DislikePostEvent($pId: postId)            
        $p: Post(postId == $pId)
    then
    	$p.dislikePost();
    	update($p);
end

rule "Post report"
	salience 10
	lock-on-active
    when        
        $e: ReportPostEvent($pId: postId)            
        $p: Post(postId == $pId)
    then
    	$p.reportPost();
    	update($p);
end

        