package rules;

import forum.model.Post;
import forum.model.User;
import forum.model.PostLabelEnum;
import forum.model.UserLabelEnum;
import forum.event.DislikePostEvent;

rule "More than 45 actions in a minute by user"
    when
        $d1: DislikePostEvent($uId: userId)
        Number(intValue >= 10) from accumulate(
            $d2: DislikePostEvent(
            	userId == $uId, 
                this meets[1m] $d1),
            count($d2)
        )
    then
        System.out.println("WARNING: Spammer user. User " + $uId);
end

