package rules;

import forum.model.Post;
import forum.model.User;
import forum.model.PostLabelEnum;
import forum.model.UserLabelEnum;

import forum.event.DislikePostEvent;
import forum.event.LikePostEvent;
import forum.event.ReportPostEvent;
import forum.event.NewPostEvent;

import forum.event.label.TopUserLabelEvent;
import forum.event.label.CommunityContributorUserLabelEvent;
import forum.event.label.SpammerUserLabelEvent;
import forum.event.label.HarmfulUserLabelEvent;
import forum.event.label.TemporarilySuspendedUserLabelEvent;
import forum.event.label.SuspendedUserLabelEvent;

import forum.event.label.TrendingPostLabelEvent;
import forum.event.label.PoorContentPostLabelEvent;
import forum.event.label.PotentiallyHarmfulPostLabelEvent;
import forum.event.label.HarmfulPostLabelEvent;

rule "More than 45 actions in a minute by user"
    when        
        $d1: DislikePostEvent($uId: userId)            
        $u: User(username == $uId, !userLabels.contains(UserLabelEnum.SPAMMER))
        Number(intValue >= 45) from accumulate(
            $d2: DislikePostEvent(
            	userId == $uId, 
                this meets[1m] $d1),
            count($d2)
        )
    then
        System.out.println("WARNING: Spammer user. User " + $u.getName());        
        insert(new SpammerUserLabelEvent($uId));
    	$u.addLabel(UserLabelEnum.SPAMMER);
    	// $u.update();
    	update($u);
        
end




        